### ISSUE TITLE
FAIL in follow the EMU Building tutorial.

### ISSUE THREAD

**Issue by yichun463** [jdeschamps/EMU#18] opened 2020-11-02 03:11 UTC
Hi there,  I could not find the EMU-1.0-SNAPSHOT.jar, which is mentioned in the tutorial , after compiling EMU into MicroManager 2.0 gamma by git bash.

**Comment by jdeschamps** [comment] 2020-11-02 14:12
Hi!

I updated the EMU-guide and tutorial: EMU is distributed with Micro-Manager 2.0.0-gamma nightly builds, so you can just download a recent nightly build and use the EMU.jar file from the Micro-Manager installation folder (in mmplugins).

Regarding your question, what is the console output when you compile EMU? 

The maven compilation creates something like EMU-1.1.jar in your local EMU git repository under "target". The compilation script just copies this file to the Micro-Manager installation folder. If the script fails but the compilation doesn't, then you can just copy the EMU jar to Micro-Manager.

**Comment by jdeschamps** [comment] 2020-11-04 16:47
Any luck?

**Comment by yichun463** [comment] 2020-11-08 14:44
sorry that replied late and thanks for your update! 
this problems have been always encountered 
![image](https://user-images.githubusercontent.com/66891774/98467562-fc247180-2210-11eb-9374-0c878c9ad5f9.png)
after I follow the 7th step.
![image](https://user-images.githubusercontent.com/66891774/98467951-342cb400-2213-11eb-9623-98a496e97015.png)
nothing is displayed when I switch to design tag.
![image](https://user-images.githubusercontent.com/66891774/98467921-034c7f00-2213-11eb-9d26-9fa1d03c1991.png)
![image](https://user-images.githubusercontent.com/66891774/98468104-e4022180-2213-11eb-91a0-2ca882ee0ac0.png)

I guess the errors above account for this. 
I will appreciate it if you can help me !

**Comment by jdeschamps** [comment] 2020-11-08 18:03
From your screen shots it seems Eclipse has somewhat not updated your project. You clearly have the abstract methods implemented, and yet it pretends in the "Problems" tab that they are not.

The first thing I woud try is just to go to "Project" in the menu bar and click on "clean". Also make sure that "Build automatically" is selected (also in "Project"). You can also try right-clicking on your project in the package explorer and click on refresh.

For reference I tried with a recent Eclipse version and the latest nightly build and could not reproduce this, but I'd put my two cents on your Eclipse not refreshing your project's status.

**Comment by yichun463** [comment] 2020-11-10 02:33
Hi
thank you for your reply and I tried your advicement and refreshed the project but the problem remained.
So I changed another version eclipse and finally it is successful to display the design interface, though the errors still exist.

I will keep following next steps in ur tutorial.
btw ,my supervisor is your former fellow and currently I 'm learning to build EMU. And I'm a freshman in java XD



















At 2020-11-09 02:03:45, "jdeschamps" <notifications@github.com> wrote:

From your screen shots it seems Eclipse has somewhat not updated your project. You clearly have the abstract methods implemented, and yet it pretends in the "Problems" tab that they are not.

The first thing I woud try is just to go to "Project" in the menu bar and click on "clean". Also make sure that "Build automatically" is selected (also in "Project"). You can also try right-clicking on your project in the package explorer and click on refresh.

For reference I tried with a recent Eclipse version and the latest nightly build and could not reproduce this, but I'd put my two cents on your Eclipse not refreshing your project's status.

**Comment by jdeschamps** [comment] 2020-11-10 11:42
Alright, good that it's solved. I will then close this issue.

Let me know if there are other troubles, or if you liked the tutorial!

**Closed by jdeschamps** 2020-11-10 11:42 UTC
